version: "2.2"
services:
  researchspace:
    image: ${RESEARCHSPACE_IMAGE}
    restart: unless-stopped
    mem_limit: ${RESEARCHSPACE_MEMORY}
    mem_reservation: ${RESEARCHSPACE_MEMORY}
    environment:
      # 1. Connect researchspace instance to blazegraph instance, in this case we use internal hostname available only inside docker-compose create network.
      # 2. Set default logging profile to log4j2, other possible options are log4j2-debug.xml, log4j2-trace.xml
      # 3-5. Create storage needed for image upload functionality
      # 6-8. Create temp storage needed for image upload functionality
      # 7. Additional options provided in .env file
      PLATFORM_OPTS: >-
        -Dconfig.environment.sparqlEndpoint=http://blazegraph:8080/blazegraph/sparql
        -Dlog4j.configurationFile=file:///var/lib/jetty/webapps/etc/log4j2.xml
        -Dconfig.storage.images.type=nonVersionedFile
        -Dconfig.storage.images.mutable=true
        -Dconfig.storage.images.root=/images
        -Dconfig.storage.tmp.type=nonVersionedFile
        -Dconfig.storage.tmp.mutable=true
        -Dconfig.storage.tmp.root=/tmp
        ${RESEARCHSPACE_OPTS}
      JAVA_OPTS: ${RESEARCHSPACE_JAVA_OPTS}

      # Used by nginx-docker-gen to generate nginx configuration to properly proxy all request that are coming from outside.
      # So if VIRTUAL_HOST is example.com, all requests to example.com will be proxied to this container
      # see https://github.com/nginx-proxy/nginx-proxy#usage
      VIRTUAL_HOST: ${RESEARCHSPACE_HOST_NAME}
    volumes:
       # mount folder where uploaded images should be stored 
       - ./researchspace/data/images:/images:rw

       # runtime data folder with config files and ad-hoc templates 
       - ./researchspace/runtime-data:/runtime-data
    volumes_from:
      - researchspace-app:ro

    depends_on:
      - blazegraph
      - digilib 
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  researchspace-app:
    image: ${RESEARCHSPACE_APP_IMAGE}

  blazegraph:
    image: ${BLAZEGRAPH_IMAGE}
    restart: unless-stopped
    mem_limit: ${BLAZEGRAPH_MEMORY}
    mem_reservation: ${BLAZEGRAPH_MEMORY}
    environment:
      JAVA_OPTS: ${BLAZEGRAPH_JAVA_OPTS}
    volumes:
     - ./blazegraph/:/blazegraph-data
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

  digilib:
    image: ${DIGILIB_IMAGE}
    restart: unless-stopped
    mem_limit: ${DIGILIB_MEMORY}
    mem_reservation: ${DIGILIB_MEMORY}
    environment:
      BASEDIR_LIST: /var/lib/images
      IIIF_IMAGE_BASE_URL: "https://${RESEARCHSPACE_HOST_NAME}/proxy/IIIF/"
    volumes:
      - ./researchspace/data/images/file:/var/lib/images:rw
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  # see https://github.com/nginx-proxy/nginx-proxy
  nginx:
    # we need to have fixed container name for nginx because currently there is no easy way to easily use docker-gen with dynamic names generated by docker-compose, see https://github.com/jwilder/docker-gen/issues/77 
    container_name: nginx
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - 443:443
      - 80:80
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

  # see https://github.com/nginx-proxy/nginx-proxy#separate-containers
  nginx-docker-gen:
    image: jwilder/docker-gen:latest
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    environment:
      DEFAULT_HOST: ${RESEARCHSPACE_HOST_NAME}
    command:
      "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

